### PR TITLE
Fix the problem of reconnecting when moved to another VC

### LINKED ISSUE #849: Can't use VoiceConnection when the bot is moved to another vc by a User
Ran into a situation where when playing a sound, if the bot was moved to another voice channel, it seemingly gets stuck in limbo. Running `Disconnect()` just crashes. `s.VoiceConnections[e.GuildID]` seems to just flat out return `nil` every time (for me at least).

I was able to sorta get around this by storing the `VoiceConnection*` as a global, then setting a custom error handler for dgvoice:
```go
dgvoice.OnError = func(str string, err error) {
	vc.Disconnect()
}
```
then setting up an event handler for `voiceStateUpdate`:
```go
if e.UserID == "bot-id" {
	if e.BeforeUpdate != nil {
		vc, _ = s.ChannelVoiceJoin(e.GuildID, e.ChannelID, false, false)
		vc.Disconnect()
	}
	return
}
```
This also requires #833 in order to work, or some manual work keeping track of the bot's previous voice channel.

Basically, if it detects the bot being moved (`e.BeforeUpdate != nil`) then it reconnects to the same channel manually, bringing it out of "limbo". Then it just disconnects.

Obviously this isn't the end of the world, but it's a pretty rough fix. Does anyone have any better approaches? My ideas are:
- Add some "fromAnotherChannel" property to `VoiceStateUpdate`, then it's at least a bit easier for users to define their wanted behavior
- Add a separate "voiceChannelMoved` event to make it even a little bit _more_ easy
- Ideally, somehow have `VoiceConnection*` update itself when moved

Thoughts?

### PR DESCRIPTION
**Pull request by nonnonstop**
Fixes #849.

## Description

When the bot was moved to another vc, the connection was disconnected with `4014 Disconnected`.

* https://github.com/Rapptz/discord.py/issues/5904
* https://github.com/discord/discord-api-docs/issues/2450
* https://github.com/discordjs/guide/blob/main/guide/voice/voice-connections.md#handling-disconnects

Then, `VOICE_SERVER_UPDATE` is received after `4014 Disconnected`.
```
2022/10/30 14:47:23 [DG2] voice.go:356:wsListen() received 4014 manual disconnection
2022/10/30 14:47:23 [DG2] voice.go:167:Close() called
2022/10/30 14:47:23 [DG2] voice.go:176:Close() closing v.close
2022/10/30 14:47:23 [DG2] voice.go:182:Close() closing udp
2022/10/30 14:47:23 [DG3] wsapi.go:547:onEvent() Op: 0, Seq: 6, Type: VOICE_STATE_UPDATE, Data: [hidden]
2022/10/30 14:47:23 [DG3] wsapi.go:547:onEvent() Op: 0, Seq: 7, Type: VOICE_SERVER_UPDATE, Data: {"token":"[hidden]","guild_id":"[hidden]","endpoint":"brazil7541.discord.media:443"}
2022/10/30 14:47:23 [DG2] wsapi.go:763:onVoiceServerUpdate() called
```

However, the VoiceConnection has been deleted when the `VOICE_SERVER_UPDATE` is received due to the following code. (L364)
https://github.com/bwmarrin/discordgo/blob/afab84009be89bd6e793dafea88a6acd89f34df9/voice.go#L355-L370

Since the VoiceConnection does not exist, `onVoiceServerUpdate` does not reconnect.

https://github.com/bwmarrin/discordgo/blob/afab84009be89bd6e793dafea88a6acd89f34df9/wsapi.go#L761-L772

This is the cause of #849.

## How to fix

Delay the time between receiving `4014 Disconnected` and deleting the connection.
If `VOICE_SERVER_UPDATE` is received during that time, the connection is not deleted.
```
2022/10/30 15:17:13 [DG2] voice.go:356:wsListen() received 4014 manual disconnection
2022/10/30 15:17:13 [DG3] wsapi.go:547:onEvent() Op: 0, Seq: 7, Type: VOICE_SERVER_UPDATE, Data: {"token":"[hidden]","guild_id":"[hidden]","endpoint":"brazil2241.discord.media:443"}
2022/10/30 15:17:13 [DG2] wsapi.go:763:onVoiceServerUpdate() called
2022/10/30 15:17:13 [DG2] voice.go:167:Close() called
2022/10/30 15:17:13 [DG2] voice.go:176:Close() closing v.close
2022/10/30 15:17:13 [DG2] voice.go:182:Close() closing udp
2022/10/30 15:17:13 [DG2] voice.go:280:open() called
2022/10/30 15:17:13 [DG2] voice.go:306:open() connecting to voice endpoint wss://brazil2241.discord.media:443
2022/10/30 15:17:13 [DG2] voice.go:348:wsListen() called
2022/10/30 15:17:13 [DG3] voice.go:417:onEvent() received: {"op":8,"d":{"v":1,"heartbeat_interval":55000}}
2022/10/30 15:17:13 [DG3] voice.go:494:onEvent() unknown voice operation, 8, {"v":1,"heartbeat_interval":55000}
2022/10/30 15:17:14 [DG2] voice.go:372:wsListen() successfully reconnected due to code 4014
```
If not (e.g. kicked by admin), the connection is deleted.
```
2022/10/30 15:18:24 [DG2] voice.go:356:wsListen() received 4014 manual disconnection
2022/10/30 15:18:29 [DG2] voice.go:376:wsListen() disconnect due to code 4014
2022/10/30 15:18:29 [DG2] voice.go:167:Close() called
2022/10/30 15:18:29 [DG2] voice.go:176:Close() closing v.close
2022/10/30 15:18:29 [DG2] voice.go:182:Close() closing udp
```

### CODE REVIEW

File: voice.go [hunk 1]
```diff
@@ -360,6 +360,25 @@ func (v *VoiceConnection) wsListen(wsConn *websocket.Conn, close <-chan struct{}
 				v.wsConn = nil
 				v.Unlock()
 
+				// Wait for VOICE_SERVER_UPDATE.
+				// When the bot is moved by the user to another voice channel,
+				// VOICE_SERVER_UPDATE is received after the code 4014.
+				for i := 0; i < 5; i++ {
+					<-time.After(1 * time.Second)
```
Comment (FedorLap2006) [inline voice.go:367]: Is there any reason why it's 5x1 second in particular?

**Review by FedorLap2006 — CHANGES_REQUESTED** [review]
LGTM, however I'm not fully sure about this `for` based retry solution

P.S. Thanks for fixing such longstanding issue!

File: voice.go (hunk 1 above)
Comment (nonnonstop) [reply voice.go:367]: The client is reconnected almost within 1 second, but I set the timeout to 5 seconds to give more leeway.

File: voice.go [hunk 2]
```diff
@@ -360,6 +360,25 @@ func (v *VoiceConnection) wsListen(wsConn *websocket.Conn, close <-chan struct{}
...
+
+					v.Lock()
+					reconnected := v.wsConn != nil
+					v.Unlock()
```
Comment (FedorLap2006) [inline voice.go:371]: Since we're only reading the wsConn value, I think it would be appropriate to use R(Un)lock here instead of regular (Un)lock.
```suggestion
					v.RLock()
					reconnected := v.wsConn != nil
					v.RUnlock()
```

**Review by FedorLap2006 — CHANGES_REQUESTED** [review]
Sorry for a long wait.

File: voice.go [hunk 3]
```diff
@@ -360,6 +360,25 @@ func (v *VoiceConnection) wsListen(wsConn *websocket.Conn, close <-chan struct{}
 				v.wsConn = nil
 				v.Unlock()
 
+				// Wait for VOICE_SERVER_UPDATE.
+				// When the bot is moved by the user to another voice channel,
+				// VOICE_SERVER_UPDATE is received after the code 4014.
+				for i := 0; i < 5; i++ {
```
Comment (FedorLap2006) [inline voice.go:366]:
```suggestion
				for i := 0; i < 5; i++ { // TODO: temp, wait for VoiceServerUpdate.
```

**Review by FedorLap2006 — APPROVED** [review]
LGTM.

P.S. About the To Do comment. I've marked this loop, since we will probably replace it with a proper solution, using our event system, sometime in the future, alongisde other unrefactored stuff.

**Comment by FedorLap2006** [comment]
Anyhow, thanks for your work and patience.
